upd: added destroy, some lil fixes

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -8,217 +8,228 @@ on:
 #   pull_request:
 #     branches: '**'
 
-build-qemu:
-  runs-on: ubuntu-latest
-  env:
-    # variables from GL CI
-    NAME: "" # Name of packer configuration file without `.json`, for example kali
-    TYPE: "" # linux or windows
-    DISTRO: "" # See https://docs.openstack.org/glance/latest/admin/useful-image-properties.html property os_distro
-    GUI_ACCESS: "true" # Whether VNC or RDP server is installed and configured for [Guacamole](https://docs.crp.kypo.muni.cz/user-guide-advanced/sandboxes/sandbox-access/#apache-guacamole)
+jobs:
+
+  build-qemu:
+    runs-on: ubuntu-latest
+    env:
+      # variables from GL CI
+      NAME: "" # Name of packer configuration file without `.json`, for example kali
+      TYPE: "" # linux or windows
+      DISTRO: "" # See https://docs.openstack.org/glance/latest/admin/useful-image-properties.html property os_distro
+      GUI_ACCESS: "true" # Whether VNC or RDP server is installed and configured for [Guacamole](https://docs.crp.kypo.muni.cz/user-guide-advanced/sandboxes/sandbox-access/#apache-guacamole)
+      
+      # .terraform-build
+      TF_ROOT: ${CI_PROJECT_DIR}
+      TF_STATE_NAME: ${CI_COMMIT_REF_SLUG}
+      TF_VAR_CI_SERVER_HOST: ${CI_SERVER_HOST}
+      TF_VAR_CI_COMMIT_SHORT_SHA: ${CI_COMMIT_SHORT_SHA}
+      
+      # deploy-qemu
+      KEY: "qemu"
+      OS_AUTH_TYPE: "v3applicationcredential"
+      OS_AUTH_URL: "https://identity.cloud.muni.cz/v3"
+      OS_IDENTITY_API_VERSION: "3"
+      OS_INTERFACE: "public"
+      OS_REGION_NAME: "brno1"
+
+      # test-qemu
+      TF_VAR_NAME: ${NAME}
+      TF_VAR_TYPE: ${TYPE}
+      TF_VAR_DISTRO: ${DISTRO}
+      TF_VAR_GUI_ACCESS: ${GUI_ACCESS}
+      TF_VAR_ACCESS_TOKEN: ${ACCESS_TOKEN}
+
+    steps:
+      # Checkout repository
+      - name: Checkout Repository
+        uses: actions/checkout@v4
+
+      # .build (install packer and some modules)
+      - name: Setup packer
+        uses: hashicorp/setup-packer@main
+        id: setup
+        with:
+          version: latest
+
+      - name: Install Packer Plugins
+        run: |
+          packer plugins install github.com/hashicorp/qemu
+          packer plugins install github.com/hashicorp/virtualbox
+          packer plugins install github.com/hashicorp/vagrant
     
-    # .terraform-build
-    TF_ROOT: ${CI_PROJECT_DIR}
-    TF_STATE_NAME: ${CI_COMMIT_REF_SLUG}
-    TF_VAR_CI_SERVER_HOST: ${CI_SERVER_HOST}
-    TF_VAR_CI_COMMIT_SHORT_SHA: ${CI_COMMIT_SHORT_SHA}
-    
-    # deploy-qemu
-    KEY: "qemu"
-    OS_AUTH_TYPE: "v3applicationcredential"
-    OS_AUTH_URL: "https://identity.cloud.muni.cz/v3"
-    OS_IDENTITY_API_VERSION: "3"
-    OS_INTERFACE: "public"
-    OS_REGION_NAME: "brno1"
 
-    # test-qemu
-    TF_VAR_NAME: ${NAME}
-    TF_VAR_TYPE: ${TYPE}
-    TF_VAR_DISTRO: ${DISTRO}
-    TF_VAR_GUI_ACCESS: ${GUI_ACCESS}
-    TF_VAR_ACCESS_TOKEN: ${ACCESS_TOKEN}
+      # Custom script from the step
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v3
 
-  steps:
-    # Checkout repository
-    - name: Checkout Repository
-      uses: actions/checkout@v4
+      - name: Work with terraform
+        run: |
+          packer build -only=qemu $NAME.json
+          terraform destroy
+          terraform plan -target=module.topology.openstack_images_image_v2.test_image
+          terraform apply
 
-    # .build (install packer and some modules)
-    - name: Setup packer
-      uses: hashicorp/setup-packer@main
-      id: setup
-      with:
-        version: latest
+  test-qemu:
+    runs-on: ubuntu-latest
+    needs: build-qemu
+    steps:
 
-    - name: Install Packer Plugins
-      run: |
-        packer plugins install github.com/hashicorp/qemu
-        packer plugins install github.com/hashicorp/virtualbox
-        packer plugins install github.com/hashicorp/vagrant
-  
+      # .terraform-build
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v3
+      
+      - name: Terraform plan & apply
+        run: |
+          terraform plan 
+          terraform apply
+        # and some stuff with artifacts (not sure)
 
-    # Custom script from the step
-    - name: Setup Terraform
-      uses: hashicorp/setup-terraform@v3
+  deploy-qemu:
+    runs-on: ubuntu-latest
+    needs: ["build-qemu", "test-qemu"]
+    env: 
+      KEY: "qemu"
+      OS_AUTH_TYPE: "v3applicationcredential"
+      OS_AUTH_URL: "https://identity.cloud.muni.cz/v3"
+      OS_IDENTITY_API_VERSION: "3"
+      OS_INTERFACE: "public"
+      OS_REGION_NAME: "brno1"
+    steps:
 
-    - name: Work with terraform
-    - run: | # TODO $NAME
-        packer build -only=qemu $NAME.json
-        terraform destroy
-        terraform plan -target=module.topology.openstack_images_image_v2.test_image
-        terraform apply
-
-test-qemu:
-  runs-on: ubuntu-latest
-  needs: build-qemu
-  steps:
-
-    # .terraform-build
-    - name: Setup Terraform
-      uses: hashicorp/setup-terraform@v3
-    
-    - name: Terraform plan & apply
-      run: |
-        terraform plan 
-        terraform apply
-      # and some shit with artifacts (not sure)
-
-deploy-qemu:
-  runs-on: ubuntu-latest
-  needs: ["build-qemu", "test-qemu"]
-  env: 
-    KEY: "qemu"
-    OS_AUTH_TYPE: "v3applicationcredential"
-    OS_AUTH_URL: "https://identity.cloud.muni.cz/v3"
-    OS_IDENTITY_API_VERSION: "3"
-    OS_INTERFACE: "public"
-    OS_REGION_NAME: "brno1"
-  steps:
-
-    # Tenplates (TODO there are some CI variables)
-    - &get-version-from-changelog
-      name: get-version-from-changelog
-      run: |
-        test ! -z "$KEY"
-        if [ -z "$VERSION" ]; then
-          VERSION=$(cat CHANGELOG.md | sed -r -e "/##\s+.*\[$KEY-[0-9]+\.[0-9]+\.[0-9]+\]/!d" -e "s/.*$KEY-([0-9]+\.[0-9]+\.[0-9]+).*/\1/" | sort --version-sort --reverse | head -n 1)
-          test ! -z "$VERSION"
-        fi
-        echo "$VERSION"
-
-    - &git-tag
-      name: git-tag
-      run: |
-        git config user.name "$GITLAB_USER_NAME"; git config user.email "$GITLAB_USER_EMAIL"
-        git tag -a "$KEY-$VERSION" -m "$KEY version $VERSION"
-        git push https://root:$ACCESS_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git "$KEY-$VERSION"
-
-    - &upload-image-to-openstack
-      name: upload-image-to-openstack
-      run: openstack image create --file target-qemu/* --property hw_scsi_model=virtio-scsi --property hw_disk_bus=scsi --property hw_rng_model=virtio --property hw_qemu_guest_agent=yes --property os_require_quiesce=yes --property os_type=$TYPE --property os_distro=$DISTRO --property owner_specified.openstack.version=$VERSION --property owner_specified.openstack.gui_access=$GUI_ACCESS --property owner_specified.openstack.created_by=munikypo --shared $CI_PROJECT_NAME-$VERSION
-    
-    # do we need it here?
-    # - &upload-image-to-openstack-object-store
-    #   name: upload-image-to-openstack-object-store
-    #   run: |
-    #     cd target-qemu
-    #     IMAGE_FILENAME=$(ls)
-    #     mv $IMAGE_FILENAME $IMAGE_FILENAME.raw
-
-    #     s3cmd -c $S3_CREDENTIALS get s3://kypo-images/SHA256SUMS SHA256SUMS
-    #     s3cmd -c $S3_CREDENTIALS get s3://kypo-images/MD5SUMS MD5SUMS
-    #     zip $CI_PROJECT_NAME.raw.zip $IMAGE_FILENAME.raw
-    #     sed -i "/$CI_PROJECT_NAME.raw.zip/d" SHA256SUMS
-    #     sha256sum $CI_PROJECT_NAME.raw.zip >> SHA256SUMS
-    #     sed -i "/$CI_PROJECT_NAME.raw.zip/d" MD5SUMS
-    #     md5sum $CI_PROJECT_NAME.raw.zip >> MD5SUMS
-
-    #     qemu-img convert -f raw -O qcow2 $IMAGE_FILENAME.raw $CI_PROJECT_NAME.qcow2
-    #     sed -i "/$CI_PROJECT_NAME.qcow2/d" SHA256SUMS
-    #     sha256sum $CI_PROJECT_NAME.qcow2 >> SHA256SUMS
-    #     sed -i "/$CI_PROJECT_NAME.qcow2/d" MD5SUMS
-    #     md5sum $CI_PROJECT_NAME.qcow2 >> MD5SUMS
-
-    #     sort -k 2 -o SHA256SUMS SHA256SUMS
-    #     sort -k 2 -o MD5SUMS MD5SUMS
-    #     s3cmd -c $S3_CREDENTIALS put $CI_PROJECT_NAME.qcow2 $CI_PROJECT_NAME.raw.zip SHA256SUMS MD5SUMS s3://kypo-images
-    #     cd -
-
-
-    # before_script
-
-    - *get-version-from-changelog
-
-    - name: something
-      run: |
-        mkdir -p target-qemu
-        openstack image save --file "target-qemu/$NAME" "$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA"
-
-    - *upload-image-to-openstack
-
-    # The custom script
-
-    - run: |
-        HEAD_IMAGE_ID=$(openstack image show --column id --format value $CI_PROJECT_NAME-$VERSION)
-        # If previous image version exists, delete it or rename it. Once all our images follow the latest naming convention, this block can be simplified
-        if openstack image show $CI_PROJECT_NAME > /dev/null; then
-          PREV_VERSION=$(openstack image show $CI_PROJECT_NAME --column properties --format json | jq '.properties."owner_specified.openstack.version"' -re) || PREV_VERSION=0.1.0
-          if openstack image show $CI_PROJECT_NAME-$PREV_VERSION > /dev/null; then
-            openstack image delete $CI_PROJECT_NAME || openstack image set $CI_PROJECT_NAME --name $CI_PROJECT_NAME-DEPRECATED
-          else
-            openstack image set $CI_PROJECT_NAME --name $CI_PROJECT_NAME-$PREV_VERSION
+      # Tenplates (TODO there are some CI variables)
+      - &get-version-from-changelog
+        name: get-version-from-changelog
+        run: |
+          test ! -z "$KEY"
+          if [ -z "$VERSION" ]; then
+            VERSION=$(cat CHANGELOG.md | sed -r -e "/##\s+.*\[$KEY-[0-9]+\.[0-9]+\.[0-9]+\]/!d" -e "s/.*$KEY-([0-9]+\.[0-9]+\.[0-9]+).*/\1/" | sort --version-sort --reverse | head -n 1)
+            test ! -z "$VERSION"
           fi
-        fi
-        openstack image set $CI_PROJECT_NAME-$VERSION --name $CI_PROJECT_NAME
+          echo "$VERSION"
 
-    - *upload-image-to-openstack
+      - &git-tag
+        name: git-tag
+        run: |
+          git config user.name "$GITLAB_USER_NAME"; git config user.email "$GITLAB_USER_EMAIL"
+          git tag -a "$KEY-$VERSION" -m "$KEY version $VERSION"
+          git push https://root:$ACCESS_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git "$KEY-$VERSION"
 
-    - run: STABLE_IMAGE_ID=$(openstack image show --column id --format value $CI_PROJECT_NAME-$VERSION)
+      - &upload-image-to-openstack
+        name: upload-image-to-openstack
+        run: openstack image create --file target-qemu/* --property hw_scsi_model=virtio-scsi --property hw_disk_bus=scsi --property hw_rng_model=virtio --property hw_qemu_guest_agent=yes --property os_require_quiesce=yes --property os_type=$TYPE --property os_distro=$DISTRO --property owner_specified.openstack.version=$VERSION --property owner_specified.openstack.gui_access=$GUI_ACCESS --property owner_specified.openstack.created_by=munikypo --shared $CI_PROJECT_NAME-$VERSION
+      
+      # do we need it here? It is used one time only
+      # - &upload-image-to-openstack-object-store
+      #   name: upload-image-to-openstack-object-store
+      #   run: |
+      #     cd target-qemu
+      #     IMAGE_FILENAME=$(ls)
+      #     mv $IMAGE_FILENAME $IMAGE_FILENAME.raw
 
-    - *git-tag
+      #     s3cmd -c $S3_CREDENTIALS get s3://kypo-images/SHA256SUMS SHA256SUMS
+      #     s3cmd -c $S3_CREDENTIALS get s3://kypo-images/MD5SUMS MD5SUMS
+      #     zip $CI_PROJECT_NAME.raw.zip $IMAGE_FILENAME.raw
+      #     sed -i "/$CI_PROJECT_NAME.raw.zip/d" SHA256SUMS
+      #     sha256sum $CI_PROJECT_NAME.raw.zip >> SHA256SUMS
+      #     sed -i "/$CI_PROJECT_NAME.raw.zip/d" MD5SUMS
+      #     md5sum $CI_PROJECT_NAME.raw.zip >> MD5SUMS
 
-    - run: |
-        Share the image to other OpenStack projects
-        while read -r PROJECT_ID; do
-          openstack image add project $HEAD_IMAGE_ID $PROJECT_ID
-          openstack image add project $STABLE_IMAGE_ID $PROJECT_ID
-        done < <(echo $APPLICATION_CREDENTIALS | jq -r '.[] | .project_id')
-        Accept the sharing from each project
-        while read -r APP_ID && read -r APP_SECRET; do
-          OS_APPLICATION_CREDENTIAL_ID=$APP_ID
-          OS_APPLICATION_CREDENTIAL_SECRET=$APP_SECRET
-          openstack image set --accept $HEAD_IMAGE_ID
-          openstack image set --accept $STABLE_IMAGE_ID
-        done < <(echo $APPLICATION_CREDENTIALS | jq -r '.[] | (.app_cred_id, .app_cred_secret)')
-        if [ $TYPE != "windows" ]; then
-          # .upload-image-to-openstack-object-store
-          cd target-qemu
-          IMAGE_FILENAME=$(ls)
-          mv $IMAGE_FILENAME $IMAGE_FILENAME.raw
+      #     qemu-img convert -f raw -O qcow2 $IMAGE_FILENAME.raw $CI_PROJECT_NAME.qcow2
+      #     sed -i "/$CI_PROJECT_NAME.qcow2/d" SHA256SUMS
+      #     sha256sum $CI_PROJECT_NAME.qcow2 >> SHA256SUMS
+      #     sed -i "/$CI_PROJECT_NAME.qcow2/d" MD5SUMS
+      #     md5sum $CI_PROJECT_NAME.qcow2 >> MD5SUMS
 
-          s3cmd -c $S3_CREDENTIALS get s3://kypo-images/SHA256SUMS SHA256SUMS
-          s3cmd -c $S3_CREDENTIALS get s3://kypo-images/MD5SUMS MD5SUMS
-          zip $CI_PROJECT_NAME.raw.zip $IMAGE_FILENAME.raw
-          sed -i "/$CI_PROJECT_NAME.raw.zip/d" SHA256SUMS
-          sha256sum $CI_PROJECT_NAME.raw.zip >> SHA256SUMS
-          sed -i "/$CI_PROJECT_NAME.raw.zip/d" MD5SUMS
-          md5sum $CI_PROJECT_NAME.raw.zip >> MD5SUMS
-
-          qemu-img convert -f raw -O qcow2 $IMAGE_FILENAME.raw $CI_PROJECT_NAME.qcow2
-          sed -i "/$CI_PROJECT_NAME.qcow2/d" SHA256SUMS
-          sha256sum $CI_PROJECT_NAME.qcow2 >> SHA256SUMS
-          sed -i "/$CI_PROJECT_NAME.qcow2/d" MD5SUMS
-          md5sum $CI_PROJECT_NAME.qcow2 >> MD5SUMS
-
-          sort -k 2 -o SHA256SUMS SHA256SUMS
-          sort -k 2 -o MD5SUMS MD5SUMS
-          s3cmd -c $S3_CREDENTIALS put $CI_PROJECT_NAME.qcow2 $CI_PROJECT_NAME.raw.zip SHA256SUMS MD5SUMS s3://kypo-images
-          cd -
-        fi
+      #     sort -k 2 -o SHA256SUMS SHA256SUMS
+      #     sort -k 2 -o MD5SUMS MD5SUMS
+      #     s3cmd -c $S3_CREDENTIALS put $CI_PROJECT_NAME.qcow2 $CI_PROJECT_NAME.raw.zip SHA256SUMS MD5SUMS s3://kypo-images
+      #     cd -
 
 
-test-qemu-cleanup:
-  steps:
-    # TODO test-qemu
-    # TODO .terraform-destroy
+      # before_script
+
+      - *get-version-from-changelog
+
+      - name: something
+        run: |
+          mkdir -p target-qemu
+          openstack image save --file "target-qemu/$NAME" "$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA"
+
+      - *upload-image-to-openstack
+
+      # The custom script
+
+      - run: |
+          HEAD_IMAGE_ID=$(openstack image show --column id --format value $CI_PROJECT_NAME-$VERSION)
+          # If previous image version exists, delete it or rename it. Once all our images follow the latest naming convention, this block can be simplified
+          if openstack image show $CI_PROJECT_NAME > /dev/null; then
+            PREV_VERSION=$(openstack image show $CI_PROJECT_NAME --column properties --format json | jq '.properties."owner_specified.openstack.version"' -re) || PREV_VERSION=0.1.0
+            if openstack image show $CI_PROJECT_NAME-$PREV_VERSION > /dev/null; then
+              openstack image delete $CI_PROJECT_NAME || openstack image set $CI_PROJECT_NAME --name $CI_PROJECT_NAME-DEPRECATED
+            else
+              openstack image set $CI_PROJECT_NAME --name $CI_PROJECT_NAME-$PREV_VERSION
+            fi
+          fi
+          openstack image set $CI_PROJECT_NAME-$VERSION --name $CI_PROJECT_NAME
+
+      - *upload-image-to-openstack
+
+      - run: STABLE_IMAGE_ID=$(openstack image show --column id --format value $CI_PROJECT_NAME-$VERSION)
+
+      - *git-tag
+
+      - run: |
+          Share the image to other OpenStack projects
+          while read -r PROJECT_ID; do
+            openstack image add project $HEAD_IMAGE_ID $PROJECT_ID
+            openstack image add project $STABLE_IMAGE_ID $PROJECT_ID
+          done < <(echo $APPLICATION_CREDENTIALS | jq -r '.[] | .project_id')
+          Accept the sharing from each project
+          while read -r APP_ID && read -r APP_SECRET; do
+            OS_APPLICATION_CREDENTIAL_ID=$APP_ID
+            OS_APPLICATION_CREDENTIAL_SECRET=$APP_SECRET
+            openstack image set --accept $HEAD_IMAGE_ID
+            openstack image set --accept $STABLE_IMAGE_ID
+          done < <(echo $APPLICATION_CREDENTIALS | jq -r '.[] | (.app_cred_id, .app_cred_secret)')
+          if [ $TYPE != "windows" ]; then
+            # .upload-image-to-openstack-object-store
+            cd target-qemu
+            IMAGE_FILENAME=$(ls)
+            mv $IMAGE_FILENAME $IMAGE_FILENAME.raw
+
+            s3cmd -c $S3_CREDENTIALS get s3://kypo-images/SHA256SUMS SHA256SUMS
+            s3cmd -c $S3_CREDENTIALS get s3://kypo-images/MD5SUMS MD5SUMS
+            zip $CI_PROJECT_NAME.raw.zip $IMAGE_FILENAME.raw
+            sed -i "/$CI_PROJECT_NAME.raw.zip/d" SHA256SUMS
+            sha256sum $CI_PROJECT_NAME.raw.zip >> SHA256SUMS
+            sed -i "/$CI_PROJECT_NAME.raw.zip/d" MD5SUMS
+            md5sum $CI_PROJECT_NAME.raw.zip >> MD5SUMS
+
+            qemu-img convert -f raw -O qcow2 $IMAGE_FILENAME.raw $CI_PROJECT_NAME.qcow2
+            sed -i "/$CI_PROJECT_NAME.qcow2/d" SHA256SUMS
+            sha256sum $CI_PROJECT_NAME.qcow2 >> SHA256SUMS
+            sed -i "/$CI_PROJECT_NAME.qcow2/d" MD5SUMS
+            md5sum $CI_PROJECT_NAME.qcow2 >> MD5SUMS
+
+            sort -k 2 -o SHA256SUMS SHA256SUMS
+            sort -k 2 -o MD5SUMS MD5SUMS
+            s3cmd -c $S3_CREDENTIALS put $CI_PROJECT_NAME.qcow2 $CI_PROJECT_NAME.raw.zip SHA256SUMS MD5SUMS s3://kypo-images
+            cd -
+          fi
+
+      # Here we are at 'cleanup'
+      - name: Destroy terraform
+        run: |
+          terraform destroy # it also calls KYPO API to destroy the SB
+          
+          # todo we probably dont need it
+          curl --header "Private-Token:${TF_PASSWORD:-$CI_JOB_TOKEN}" --request DELETE "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/${TF_STATE_NAME}" || true
+
+
+
+  # test-qemu-cleanup:
+  #   steps:
+  #     # TODO test-qemu
+  #     # TODO .terraform-destroy
 
